# Generated by Django 2.1 on 2018-09-04 12:18

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180828_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
